services:
  - type: web
    name: springboot-app
    # Remove the 'runtime' line completely - Render detects Java automatically
    plan: free
    branch: main
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 11