services:
  - type: web
    name: springboot-app
    runtime: java  # Required for Java apps on Render
    plan: free
    branch: main
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 11
      - key: SERVER_PORT
        value: $PORT  # Required for Render's dynamic port assignment