services:
  - type: web
    name: springboot-app
    runtime: docker
    plan: free
    branch: main
    # No buildCommand needed - Docker handles everything
    envVars:
      - key: PORT
        value: 8080